# Fichas --man para C#: errores del compilador, advertencias y frameworks (prioridad alta).
# Claves = regex exactas de explain/patterns/csharp*.py

from __future__ import annotations

from typing import Any


def _(
    mal: str,
    bien: str,
    que: str,
    regla: str,
) -> dict[str, Any]:
    return {
        "codigo_incorrecto": mal,
        "codigo_correcto": bien,
        "que_paso": que,
        "regla": regla,
    }


CAPSULES_CSHARP_HANDWRITTEN: dict[str, dict[str, Any]] = {
    # --- Errores CS (csharp.py) ---
    r"CS0103:.*does not exist in the current context": _(
        "void M() { Console.WriteLine(x); }",
        "int x = 1;\nvoid M() { Console.WriteLine(x); }",
        "El nombre no existe en este ámbito: typo, falta de campo/local, o using.",
        "Revisá `using`, calificación `Clase.Miembro`, y que el miembro exista y sea accesible.",
    ),
    r"CS0246:.*type or namespace name .* could not be found": _(
        "List<int> xs = new();",
        "using System.Collections.Generic;\nList<int> xs = new();",
        "No se resuelve el tipo: falta `using`, typo, o referencia al ensamblado.",
        "`dotnet add package` / ProjectReference y el `using` del namespace correcto.",
    ),
    r"CS1061:.*does not contain a definition for": _(
        """var s = "a";
s.Append("b");""",
        """var s = "a";
s += "b";""",
        "No hay ese método o propiedad; extension methods requieren `using` del namespace.",
        "IntelliSense/API del tipo; `using` de static class de extensiones.",
    ),
    r"CS0029:.*Cannot implicitly convert type": _(
        "string s = 42;",
        "string s = 42.ToString();",
        "No existe conversión implícita entre esos tipos.",
        "Cast explícito, `Parse`/`TryParse`, o cambiá el tipo de la variable.",
    ),
    r"CS0026:.*keyword.*this.*static": _(
        "static void F() { this.X = 1; }",
        "void F() { this.X = 1; }  // método de instancia",
        "`this` no existe en miembros estáticos.",
        "Hacé el método de instancia o pasá el objeto como parámetro.",
    ),
    r"CS0101:.*namespace.*already contains a definition": _(
        "namespace N { class A {} class A {} }",
        "namespace N { class A {} class B {} }",
        "Dos tipos con el mismo nombre en el mismo namespace.",
        "Renombrá uno; `partial` solo si es intencional el mismo tipo.",
    ),
    r"CS0111:.*already defines a member": _(
        "class C { void M() {} void M() {} }",
        "class C { void M(int x) {} void M(string s) {} }",
        "Dos miembros con la misma firma.",
        "Sobrecarga válida = distintos parámetros; eliminá duplicados.",
    ),
    r"CS0122:.*inaccessible due to its protection level": _(
        "other.Helper();  // Helper es private en otra clase",
        "internal/public según ensamblado; o método público en la API.",
        "`private`/`protected` impide el acceso desde aquí.",
        "Expone API pública, `InternalsVisibleTo`, o refactor de encapsulación.",
    ),
    r"CS0162:.*Unreachable code": _(
        "return;\nConsole.WriteLine(1);",
        "Console.WriteLine(1);\nreturn;",
        "Código después de `return`/`throw` inalcanzable.",
        "Eliminá código muerto o corregí el flujo.",
    ),
    r"CS0234:.*does not exist in the namespace": _(
        "using System;\nX.StringBuilder sb;",
        "using System;\nusing System.Text;\nStringBuilder sb = new();",
        "El subnombre no existe bajo ese namespace.",
        "`using` del namespace anidado correcto (p. ej. `System.Text`).",
    ),
    r"CS0246:.*could not be found \(are you missing": _(
        "// error sugiere using X",
        "using X;  // o referencia de proyecto",
        "CS0246 con pista explícita del compilador.",
        "Seguí la sugerencia del mensaje (using o referencia).",
    ),
    r"CS0311:.*cannot be used as type parameter": _(
        "class Box<T> where T : struct { }\nclass X { }\nBox<X> b;",
        "Box<int> b;",
        "El argumento de tipo no cumple la restricción `where`.",
        "Ajustá el tipo concreto o relajá/ampliá las restricciones del genérico.",
    ),
    r"CS0400:.*could not be found in the global namespace": _(
        "global::NoExiste x;",
        "global::System.Console.WriteLine(1);",
        "El nombre tras `global::` no existe.",
        "Solo usá `global::` con namespaces reales; evitá alias rotos.",
    ),
    r"CS0413:.*field.*assigned but its value is never used": _(
        "readonly int x = 1; // nunca leído",
        "readonly int x = 1;\nvoid M() => Console.WriteLine(x);",
        "Campo asignado pero nunca leído (a veces warning nivel error).",
        "Usalo, eliminálo, o documentá con `#pragma`/atributo si es intencional.",
    ),
    r"CS0535:.*does not implement interface member": _(
        "class C : IDisposable { }",
        "class C : IDisposable { public void Dispose() { } }",
        "Falta implementar miembro(s) de la interfaz.",
        "Implementá todos los miembros o hacé la clase abstracta.",
    ),
    r"CS0542:.*member names cannot be the same as their enclosing type": _(
        "class Foo { public int Foo => 1; }",
        "class Foo { public int Value => 1; }",
        "Miembro no puede llamarse igual que el tipo contenedor.",
        "Renombrá propiedad/método o el tipo.",
    ),
    r"CS0552:.*conversion routines must take one parameter": _(
        "public static implicit operator int(A a) => 1;\npublic static implicit operator int(A a, int x) => 1;",
        "public static implicit operator int(A a) => 1;",
        "Operadores de conversión deben tener exactamente un parámetro.",
        "Un solo parámetro del tipo fuente.",
    ),
    r"CS0708:.*static classes cannot have instance constructors": _(
        "static class U { public U() {} }",
        "static class U { static U() {} }",
        "Clase `static` no puede tener ctor de instancia.",
        "Constructor estático opcional; lógica en métodos estáticos.",
    ),
    r"CS0815:.*cannot assign void to an implicitly-typed variable": _(
        "var x = Console.WriteLine(\"\");",
        "Console.WriteLine(\"\");",
        "`var` no puede inferirse desde `void`.",
        "No asignes el resultado de métodos void.",
    ),
    r"CS1002:.*; expected": _(
        "int x = 1",
        "int x = 1;",
        "Falta `;` o hay error previo que confunde al parser.",
        "Revisá la línea anterior y balance de `{}`.",
    ),
    r"CS1513:.*} expected": _(
        "class C { void M() { if (true) { ",
        "class C { void M() { if (true) { } } }",
        "Falta `}` para cerrar bloque.",
        "Balanceá llaves y paréntesis.",
    ),
    r"CS1612:.*Cannot modify the return value": _(
        "struct S { public int X; }\nS F() => new();\nvoid G() { F().X = 1; }",
        "var s = F();\ns.X = 1;",
        "No podés mutar un campo de un struct devuelto por propiedad/método (copia temporal).",
        "Guardá en variable local y modificá esa copia; o usá `class` si necesitás referencia.",
    ),
    r"CS1503:.*Argument.*cannot convert from": _(
        "void F(int x) {}\nF(\"a\");",
        "void F(int x) {}\nF(1);",
        "El argumento no convierte al tipo del parámetro.",
        "Cast, sobrecarga correcta, o corregí el tipo del argumento.",
    ),
    r"CS1501:.*No overload for method.*takes": _(
        "Console.WriteLine(1, 2, 3, 4, 5);",
        "Console.WriteLine(\"{0} {1}\", 1, 2);",
        "Ninguna sobrecarga coincide con la cantidad/tipos de argumentos.",
        "Revisá sobrecargas disponibles en la documentación.",
    ),
    r"CS0165:.*Use of unassigned local variable": _(
        "int x;\nConsole.WriteLine(x);",
        "int x = 0;\nConsole.WriteLine(x);",
        "Variable local leída antes de asignar en todos los caminos.",
        "Inicializá al declarar o asigná en todas las ramas.",
    ),
    r"CS8600:|CS8602:|CS8603:|CS8604:|CS8618:|CS8629:": _(
        "#nullable enable\nstring? s = null;\nint n = s.Length;",
        "#nullable enable\nstring? s = null;\nint n = s?.Length ?? 0;",
        "Nullable reference types: posible null o asignación null a no-nullable.",
        "`?.`, `!` con invariante, `required`, inicialización en ctor.",
    ),
    r"CS4014:.*not awaited": _(
        "async Task T() => await Task.Delay(1);\nvoid C() { T(); }",
        "async Task C() { await T(); }",
        "Llamás async sin await; errores pueden perderse.",
        "`await`, `Wait()` con cuidado, o `_ = T()` documentado fire-and-forget.",
    ),
    r"CS1998:.*async method lacks.*await": _(
        "async Task M() { return; }",
        "Task M() { return Task.CompletedTask; }",
        "`async` sin `await` suele ser innecesario.",
        "Quitá `async` o agregá `await` real.",
    ),
    r"CS5001:.*does not contain.*Main.*suitable entry point": _(
        "// librería sin Main ni top-level",
        "// añadí static void Main o top-level en el ejecutable",
        "Proyecto ejecutable sin punto de entrada.",
        "`Main` o top-level statements en un solo archivo de entrada.",
    ),
    r"CS8802:.*Only one compilation unit can have top-level statements": _(
        "// dos archivos .cs con sentencias sueltas",
        "// un solo archivo con top-level; el resto con Main o solo tipos",
        "Solo una unidad puede tener top-level statements.",
        "Consolidá o mové a `Main`.",
    ),
    r"CS0579:.*Duplicate.*attribute": _(
        "[Serializable][Serializable] class C {}",
        "[Serializable] class C {}",
        "Atributo duplicado donde no se permite.",
        "Eliminá el duplicado.",
    ),
    r"CS0840:.*must declare a body|abstract.*cannot have body": _(
        "abstract class A { public abstract void M() { } }",
        "abstract class A { public abstract void M(); }",
        "`abstract` sin cuerpo; métodos con cuerpo no pueden ser abstract mal mezclados.",
        "Seguí reglas abstract/override/sealed del lenguaje.",
    ),
    r"CS1729:.*does not contain a constructor": _(
        "new Foo(1);  // Foo solo tiene ctor sin args",
        "new Foo();",
        "Ningún constructor coincide con los argumentos.",
        "Añadí ctor o pasá los args que existen.",
    ),
    r"CS7036:.*There is no argument given that corresponds to the required parameter": _(
        "record R(int A);\nvar x = new R();",
        "var x = new R(1);",
        "Falta parámetro requerido (records posicionales, etc.).",
        "Pasá todos los required o usá `default` donde aplique.",
    ),
    r"CS8209:.*A value of type 'void' may not be assigned": _(
        "var x = () => Console.WriteLine();",
        "Action x = () => Console.WriteLine();",
        "Asignás `void` a variable.",
        "Usá `Action`/`Func` según retorno.",
    ),
    r"CS8917:.*delegate type could not be inferred": _(
        "M(x => x);  // ambiguo para el compilador",
        "M((int x) => x);",
        "No se infiere el tipo del lambda/delegate.",
        "Tipá parámetros o destino del delegate explícitamente.",
    ),
    r"MSB3644:|MSB4018:": _(
        "# error de MSBuild / targeting pack",
        "# instalar SDK o targeting pack; revisar TargetFramework en .csproj",
        "MSBuild: SDK o pack de referencia faltante, o tarea falló.",
        "`dotnet --list-sdks`, instalar workload, revisar `TargetFramework`.",
    ),
    r"CS1001:.*Identifier expected": _(
        "int ;",
        "int x;",
        "Falta identificador donde el parser lo espera.",
        "Revisá comas, genéricos y palabras clave mal colocadas.",
    ),
    r"CS1003:.*Syntax error": _(
        "int x = ;",
        "int x = 0;",
        "Token inesperado o faltante.",
        "Paréntesis, punto y coma, expresiones completas.",
    ),
    r"CS1525:.*Invalid expression term": _(
        "var x = * 3;",
        "var x = 3;",
        "Término de expresión inválido en esa posición.",
        "Revisá operadores y literales.",
    ),
    r"CS1591:.*Missing XML comment": _(
        "/// proyecto exige documentación XML",
        "/// <summary>Desc.</summary>\npublic void M() {}",
        "Proyecto con generación XML y reglas estrictas.",
        "Añadí `///` o ajustá opciones de documentación en el csproj.",
    ),
    r"CS1997:.*async.*cannot return a value": _(
        "async void M() { return 1; }",
        "async Task<int> M() { return 1; }",
        "`async void` no retorna valor al llamador como Task.",
        "Usá `async Task`/`Task<T>` salvo event handlers.",
    ),
    r"CS8072:.*expression tree.*contains": _(
        "Expression<Func<int>> e = () => M();",
        "Expression<Func<int>> e = () => 42;",
        "Árboles de expresión no pueden contener ciertas llamadas.",
        "Simplificá la lambda o usá compilación en runtime sin Expression.",
    ),
    r"CS8121:.*expression of type.*cannot be handled": _(
        "object o = 1;\nswitch (o) { case string s: break; }",
        "if (o is string s) { }",
        "Pattern no aplica al tipo en runtime en ese contexto.",
        "Revisá orden de patterns y tipos reales.",
    ),
    r"CS8509:.*not exhaustive": _(
        "int x = 1;\nvar y = x switch { 0 => \"a\" };",
        "var y = x switch { 0 => \"a\", _ => \"b\" };",
        "Switch expression no cubre todos los valores posibles.",
        "Añadí brazo `_` o todos los casos del enum.",
    ),
    r"CS8767:.*nullability.*mismatch": _(
        "#nullable enable\npublic override string? M() => null;",
        "Alineá nullability de override con la base.",
        "Contrato nullable del override no coincide con el miembro virtual/interfaz.",
        "Misma anotación `?` y `notnull` que la firma base.",
    ),
    r"CS9195:.*file-scoped namespace": _(
        "namespace A; namespace B; // dos file-scoped",
        "namespace A;  // un solo file-scoped por archivo",
        "Solo un file-scoped namespace por archivo.",
        "Un namespace por archivo o usá bloques `{}` anidados.",
    ),
    r"CS0229:.*ambiguity|is ambiguous between": _(
        "class B : A, I { void M() { base.X(); } }",
        "Calificá cuál X con interface explícita o base.",
        "Ambigüedad entre miembros heredados.",
        "Cast explícito a interfaz o `base.`.",
    ),
    r"CS0051:.*inconsistent accessibility": _(
        "public class C { private class N { } public N Get() => default; }",
        "public class C { public class N { } public N Get() => default; }",
        "Tipo público expone tipo menos accesible.",
        "Hacé pública la parte interna o el retorno menos visible.",
    ),
    r"CS1540:.*cannot access protected member": _(
        "class D : B { void M(B o) { o.Protected(); } }",
        "class D : B { void M() { Protected(); } }",
        "Protected solo accesible vía `this` o derivada, no desde otra instancia base.",
        "Patrón de acceso según reglas C#.",
    ),
    r"CS0177:.*out parameter|control leaves.*out parameter": _(
        "void M(out int x) { return; }",
        "void M(out int x) { x = 0; }",
        "Parámetro `out` debe asignarse antes de salir.",
        "Asigná `out` en todos los caminos.",
    ),
    r"CS1622:.*cannot return a value from an iterator": _(
        "IEnumerable<int> G() { yield return 1; return 2; }",
        "IEnumerable<int> G() { yield return 1; yield break; }",
        "Iterador: usá `yield return`/`yield break`, no `return` con valor mezclado mal.",
        "Seguí el patrón de iteradores.",
    ),
    r"CS8370:.*feature.*not available|required language version": _(
        "if (o is int x) { }  // en LangVersion antigua",
        "<LangVersion>latest</LangVersion> o patrón compatible.",
        "La sintaxis requiere versión de lenguaje más nueva.",
        "Subí `LangVersion` en csproj o reescribí sin la feature.",
    ),
    r"CS0161:.*not all code paths return a value": _(
        "int F(bool b) { if (b) return 1; }",
        "int F(bool b) { if (b) return 1; return 0; }",
        "Función con valor de retorno: falta `return` en algún camino.",
        "Cubrí todos los caminos o lanzá excepción en imposibles.",
    ),
    r"CS0236:.*field initializers cannot reference": _(
        "int a = b; int b = 1;",
        "int b = 1; int a = b;",
        "Inicializador de campo no puede referenciar otro campo instancia en cierto orden.",
        "Reordená o inicializá en ctor.",
    ),
    r"CS0841:.*Cannot use local variable": _(
        "Console.WriteLine(x);\nint x = 1;",
        "int x = 1;\nConsole.WriteLine(x);",
        "Uso de local antes de declarar (reglas de definite assignment).",
        "Declará antes de usar.",
    ),
    r"CS0200:.*Property or indexer.*cannot be assigned to": _(
        "public int P { get; }\nvoid M(C c) { c.P = 1; }",
        "public int P { get; set; }",
        "Propiedad sin setter o solo get calculado.",
        "Añadí `set` o usá ctor/backing field mutable.",
    ),
    r"CS1504:.*Source file.*could not be opened": _(
        "// #line o archivo en csproj no existe",
        "Corregí ruta del fuente o del link.",
        "No se pudo abrir un archivo fuente referenciado.",
        "Rutas del proyecto y archivos incluidos.",
    ),
    r"NETSDK1045:|The current .NET SDK does not support": _(
        "<TargetFramework>net10.0</TargetFramework>  # sin SDK",
        "Instalá el SDK o bajá TargetFramework soportado.",
        "El SDK instalado no soporta ese TFM.",
        "`dotnet --list-sdks` y alinear TFM con SDK instalado.",
    ),
    # --- Advertencias (csharp_warnings.py) ---
    r"warning CS0168:.*is declared but never used": _(
        "void M() { var x = 1; }",
        "void M() { }",
        "Variable local declarada y no usada.",
        "Eliminá o usá `_ =` / prefijo `_`.",
    ),
    r"warning CS0219:.*assigned but its value is never used": _(
        "var x = 1; x = 2;",
        "var x = 2;",
        "Asignación inicial nunca leída antes de reasignar.",
        "Simplificá o eliminá la primera asignación.",
    ),
    r"warning CS0414:.*assigned but its value is never read": _(
        "class C { int x = 1; }",
        "class C { int x = 1; int F() => x; }",
        "Campo privado asignado pero nunca leído.",
        "Usalo o eliminálo.",
    ),
    r"warning CS0649:.*never assigned to": _(
        "struct S { int x; }",
        "struct S { public int x; }  // o inicializá en ctor",
        "Campo nunca asignado (struct puede quedar con basura).",
        "Inicializá en ctor o valor en sitio.",
    ),
    r"warning CS4014:.*not awaited": _(
        "Task.Run(() => {});",
        "await Task.Run(() => {});",
        "Mismo caso que CS4014 en modo warning.",
        "`await` o descartar explícito.",
    ),
    r"warning CS8600:": _(
        "string s = MaybeNull();",
        "string? s = MaybeNull();",
        "Asignación posible null a tipo no nullable.",
        "Tipá como `?` o validá antes.",
    ),
    r"warning CS8602:": _(
        "void F(string? s) { Console.WriteLine(s.Length); }",
        "Console.WriteLine(s?.Length ?? 0);",
        "Desreferencia posible null.",
        "`?.` o comprobación.",
    ),
    r"warning CS8618:": _(
        "class C { public string P { get; set; } }",
        "public required string P { get; set; }  // o = \"\";",
        "Propiedad/campo non-nullable no inicializado en ctor.",
        "`required`, valor por defecto, o ctor que asigne.",
    ),
    r"warning CS8625:": _(
        "string s = null!;",
        "string? s = null;",
        "Literal null a tipo no nullable.",
        "Usá `?` o `null!` solo si hay invariante.",
    ),
    r"warning CS8601:": _(
        "string x = maybe;",
        "string? x = maybe;",
        "Asignación posible null a non-nullable.",
        "Alineá nullability.",
    ),
    r"warning CS8619:": _(
        "// valores nullability no coinciden en asignación genérica",
        "Revisá `?` en type arguments.",
        "Nullability en tipos de tupla/genérico no coincide.",
        "Ajustá anotaciones `?` y `notnull`.",
    ),
    r"warning CS8765:": _(
        "# nullable mismatch en override de parámetro",
        "Igualá anotaciones con el miembro base.",
        "Nullability del parámetro en override no coincide con base.",
        "Misma firma nullable que virtual/interfaz.",
    ),
    r"warning CS1998:": _(
        "async Task M() { }",
        "Task M() => Task.CompletedTask;",
        "async sin await (warning).",
        "Quitá async o agregá await.",
    ),
    r"warning CS0162:.*Unreachable code": _(
        "return;\nFoo();",
        "Eliminá Foo.",
        "Código inalcanzable (warning).",
        "Limpieza de código muerto.",
    ),
    r"warning CS8321:": _(
        "void M() { int x = 1; void L() { int x = 2; } }",
        "Renombrá sombra o usá local function con cuidado.",
        "Local function declarada pero no usada o sombra confusa.",
        "Invocá la local function o eliminála.",
    ),
    r"\bwarning MSB\d{3,5}:": _(
        "# MSBuild warning en build",
        "Leé el código MSB en docs de MSBuild.",
        "Advertencia de MSBuild (props, targets, copia de archivos).",
        "Diagnóstico en el texto del warning y csproj.",
    ),
    # --- Frameworks (csharp_frameworks.py) ---
    r"Microsoft\.EntityFrameworkCore\.DbUpdateException": _(
        "// SaveChanges sin manejar constraint",
        "try { ctx.SaveChanges(); } catch (DbUpdateException ex) { /* InnerException SQL */ }",
        "EF Core: violación al persistir (unique, FK, etc.).",
        "Inspeccioná `InnerException`; datos y Fluent API.",
    ),
    r"DbUpdateConcurrencyException": _(
        "// otro proceso modificó la fila",
        "Reload(); SaveChanges();  // o política de merge",
        "Token de concurrencia (rowversion) no coincide.",
        "Manejo de conflicto y reintento.",
    ),
    r"InvalidOperationException.*(DbContext|DbSet|OnModelCreating|cannot be used)": _(
        "// DbContext usado después de Dispose",
        "await using var ctx = factory.CreateDbContext();",
        "Contexto disposed o uso inválido del modelo.",
        "Scopes de DI y lifetime del DbContext.",
    ),
    r"SqlException|Microsoft\.Data\.SqlClient\.SqlException": _(
        "// error del motor SQL Server",
        "Leé Number y State en la excepción; cadena de conexión y query.",
        "Error devuelto por SQL Server.",
        "Códigos de error SQL, timeouts, deadlocks.",
    ),
    r"Npgsql\.|PostgresException": _(
        "// SqlState Postgres",
        "Inspeccioná SqlState y mensaje de Npgsql.",
        "Error del servidor PostgreSQL.",
        "Connection string, SSL, y códigos SQLSTATE.",
    ),
    r"Some services are not able to be constructed|Unable to resolve service for type": _(
        "// falta services.AddScoped<IMy, My>();",
        "builder.Services.AddScoped<IMy, My>();",
        "DI de ASP.NET Core: servicio no registrado o ciclo.",
        "Registrá interfaces; detectá dependencias circulares.",
    ),
    r"System\.AggregateException.*One or more errors occurred": _(
        "Task.WaitAll(t1, t2);  // fallos dentro",
        "ex.Flatten().InnerExceptions",
        "Varias tareas fallaron encapsuladas.",
        "Revisá InnerExceptions o await individual.",
    ),
    r"Xunit\.Sdk\.|Xunit\.Runner": _(
        "[Fact] void T() { Assert.True(false); }",
        "Corregí expectativa o datos del test.",
        "xUnit: assert o descubrimiento de tests.",
        "Mensaje de assert y target framework.",
    ),
    r"NUnit\.Framework\.(AssertionException|IgnoreException)|NUnit\.Engine\.NUnitEngineException": _(
        "Assert.That(x, Is.EqualTo(1));",
        "Ajustá expected/actual.",
        "NUnit: fallo de assert o motor.",
        "Salida Expected vs Actual.",
    ),
    r"Newtonsoft\.Json\.(JsonSerializationException|JsonReaderException|JsonWriterException)": _(
        "JsonConvert.DeserializeObject<T>(\"{\"\");",
        "JSON válido y propiedades alineadas al modelo.",
        "Json.NET: texto o modelo incompatible.",
        "`JsonProperty`, contrato de nombres, `MissingMemberHandling`.",
    ),
    r"System\.Text\.Json\.(JsonException|JsonSerializerException)": _(
        "JsonSerializer.Deserialize<T>(json);",
        "JsonPropertyName, opciones NamingPolicy, ReferenceHandler.",
        "System.Text.Json: serialización/deserialización.",
        "Opciones globales y atributos en propiedades.",
    ),
    r"AutoMapper\.AutoMapperMappingException|AutoMapperConfigurationException": _(
        "mapper.Map<Dst>(src);  // sin CreateMap",
        "CreateMap<Src, Dst>(); ValidateConfiguration();",
        "Falta mapa o configuración inválida.",
        "`CreateMap` y `AssertConfigurationIsValid` en tests.",
    ),
    r"Swashbuckle|Swashbuckle\.AspNetCore|NSwag": _(
        "// conflicto de SchemaId o tipos anónimos",
        "CustomSchemaIds o tipos explícitos en endpoints.",
        "Generación OpenAPI falló.",
        "Documentación Swashbuckle/NSwag para schema conflicts.",
    ),
    r"Microsoft\.AspNetCore\.(Routing|Mvc).*ambiguous|AmbiguousMatchException": _(
        "// dos rutas iguales",
        "HTTP method, orden, plantillas más específicas.",
        "Dos endpoints coinciden con la petición.",
        "Diferenciá por verbo, ruta o constraints.",
    ),
    r"AntiforgeryValidationException|Antiforgery.*token": _(
        "POST sin token antiforgery",
        "@Html.AntiForgeryToken() + [ValidateAntiForgeryToken]",
        "CSRF token inválido o ausente.",
        "Cookie + header/form token alineados; SameSite.",
    ),
    r"Microsoft\.IdentityModel|JwtSecurityToken|IDX\d+": _(
        "ValidateToken(...) falla",
        "Authority, Audience, IssuerSigningKey, reloj del sistema.",
        "JWT: firma, audiencia, expiración o metadatos.",
        "Configuración de `JwtBearer` y claves.",
    ),
    r"StackExchange\.Redis\.RedisConnectionException|RedisTimeoutException": _(
        "ConnectionMultiplexer.Connect(...) falla",
        "cadena de conexión, abortConnect=false, firewall",
        "Redis inalcanzable o timeout.",
        "Multiplexer singleton y timeouts del thread pool.",
    ),
    # --- ASP.NET Core, hosting, HTTP ---
    r"Microsoft\.AspNetCore\.Http\.BadHttpRequestException": _(
        "// POST sin Content-Length o body cortado",
        "app.Run(async ctx => { await ctx.Request.Body.CopyToAsync(Stream.Null); }); // consumir body",
        "Kestrel rechazó la petición HTTP (formato, tamaño, línea de request).",
        "Revisá límites en KestrelServerLimits y que el cliente envíe headers/body válidos.",
    ),
    r"Microsoft\.AspNetCore\.Connections\.AddressInUseException": _(
        "builder.WebHost.UseUrls(\"http://localhost:5000\");  // ya ocupado",
        "Cambiá puerto o liberá el proceso que escucha (lsof, netstat).",
        "El puerto de escucha ya está en uso.",
        "Un solo listener por puerto; coordiná launchSettings y contenedores.",
    ),
    r"Microsoft\.AspNetCore\.Server\.Kestrel\.|BadHttpRequestException.*Kestrel": _(
        "// HTTPS dev cert inválido o Listen mal configurado",
        "dotnet dev-certs https --trust  // o ConfigureHttps en Kestrel",
        "Error en el servidor Kestrel (TLS, límites, transport).",
        "ConfigureKestrel y certificados; revisá logs con nivel Debug.",
    ),
    r"Microsoft\.Extensions\.Hosting\.HostAbortedException|BackgroundServiceExceptionBehavior": _(
        "// IHostedService lanza en ExecuteAsync",
        "try/catch en ExecuteAsync; o StopHost sin rethrow según política",
        "El host se detuvo o un BackgroundService falló.",
        "Manejo de excepciones en servicios en segundo plano y timeouts de shutdown.",
    ),
    r"Microsoft\.AspNetCore\.Routing\.Matching\.AmbiguousMatchException": _(
        "app.MapGet(\"/a\", () => 1); app.MapGet(\"/a\", () => 2);",
        "Diferenciá con método HTTP, route pattern o Order en minimal APIs.",
        "Dos endpoints coinciden con la misma URL.",
        "Hacé rutas más específicas o asigná Order explícito.",
    ),
    r"Microsoft\.AspNetCore\.Mvc\.Infrastructure\.AmbiguousActionException|AmbiguousMatchException.*action": _(
        "// Dos [HttpGet] iguales en el mismo controller",
        "[HttpGet(\"list\")] vs [HttpGet(\"detail/{id}\")]",
        "MVC encontró más de una acción aplicable.",
        "Plantillas de ruta y verbos HTTP inequívocos.",
    ),
    r"InvalidOperationException.*endpoint|No endpoint matches|The request matched multiple endpoints": _(
        "app.UseEndpoints(_ => { });  // sin MapControllers",
        "app.MapControllers();  // después de UseRouting",
        "El enrutador no encontró endpoint o encontró varios sin desempate.",
        "Orden: UseRouting → Auth → UseEndpoints/Map*; revisá fallback.",
    ),
    r"Microsoft\.AspNetCore\.Authentication\.AuthenticationFailureException": _(
        "await HttpContext.AuthenticateAsync(\"Bearer\");  // token inválido",
        "Validá Authority, Audience y reloj del sistema; claves de firma.",
        "El handler de autenticación rechazó credenciales.",
        "Logs del middleware JwtBearer/Cookie y configuración de esquema.",
    ),
    r"Microsoft\.AspNetCore\.Authorization\.(AuthorizationMiddlewareResultHandler|AuthorizationHandlerContext)|ForbidResult|ChallengeResult": _(
        "[Authorize(Roles = \"Admin\")] sin rol en claims",
        "Policy correcta o claims en el token/cookie",
        "Usuario autenticado pero sin permiso (403) o challenge 401.",
        "Policies, handlers y requisitos de claims alineados con tu emisor de identidad.",
    ),
    r"AntiforgeryValidationException|AntiforgeryToken|The antiforgery token": _(
        "fetch('/api', { method: 'POST', body })  // sin antiforgery",
        "Headers RequestVerificationToken + cookie .AspNetCore.Antiforgery",
        "Token CSRF inválido o cookie no enviada (SameSite/cross-origin).",
        "AddAntiforgery; en SPAs alineá header y cookie con CORS.",
    ),
    r"Microsoft\.AspNetCore\.Http\.Features\.BadHttpRequestFeature|Request body too large": _(
        "[RequestSizeLimit(100_000_000)] insuficiente",
        "Options.MultipartBodyLengthLimit o Kestrel MaxRequestBodySize",
        "El cuerpo supera el límite configurado.",
        "Subí límites con criterio de seguridad o usá streaming/chunked upload.",
    ),
    r"InvalidOperationException.*form content type|Unexpected end of Stream|MultipartReader": _(
        "IFormFile sin multipart/form-data",
        "[FromForm] y cliente con FormData y boundary correcto",
        "Lectura de multipart corrupta o doble lectura del body.",
        "EnableBuffering si necesitás leer el body más de una vez.",
    ),
    # --- FastEndpoints, Carter, validación ---
    r"FastEndpoints\.[A-Za-z_]+Exception|FastEndpoints\.ValidatorExecutor": _(
        "public class MyReq { public string Name { get; set; } }  // sin validator",
        "class MyVal : AbstractValidator<MyReq> { RuleFor(x => x.Name).NotEmpty(); }",
        "FastEndpoints: validación o registro de endpoint falló.",
        "Validators en DI scoped; SendErrorsAsync para 400 consistentes.",
    ),
    r"FluentValidation\.ValidationException|FluentValidation\.AsyncValidatorInvokedSynchronouslyException": _(
        "RuleFor(x => x).MustAsync(...);  // pero Validate() síncrono",
        "await validator.ValidateAsync(model);",
        "Reglas async usadas en validación síncrona o modelo inválido.",
        "Pipeline que llame ValidateAsync; reglas Must vs MustAsync coherentes.",
    ),
    r"Carter\.|ICarterModule": _(
        "// olvidás AddCarter()",
        "builder.Services.AddCarter(); app.MapCarter();",
        "Módulo Carter no registrado o ruta duplicada entre módulos.",
        "Un AddCarter y MapCarter; revisá IHasModuleParametrization si aplica.",
    ),
    r"MediatR\.|Handler was not found for request|No service for type.*IRequestHandler": _(
        "mediator.Send(new MyCommand());  // sin handler registrado",
        "services.AddMediatR(c => c.RegisterServicesFromAssemblyContaining<Program>());",
        "No hay IRequestHandler<TRequest,TResponse> en el contenedor DI.",
        "Registrá el assembly de handlers; el tipo del request debe coincidir exactamente.",
    ),
    r"Polly\.(CircuitBreaker\.)?BrokenCircuitException|Polly\.Timeout\.TimeoutRejectedException|Polly\.RateLimit\.RateLimitRejectedException": _(
        "HttpClient con circuit abierto tras muchos 500",
        "HandleTransientHttpError + WaitAndRetry; revisá duración de break",
        "Polly cortó llamadas: circuito abierto, timeout o rate limit.",
        "Ajustá políticas por servicio; no enmascares errores de configuración.",
    ),
    r"Refit\.ApiException|Refit\.ValidationApiException": _(
        "await api.GetUserAsync(0);  // API devuelve 404",
        "try/catch ApiException; leé StatusCode y Content",
        "Refit: HTTP de error o deserialización distinta al contrato.",
        "ApiResponse<T>, serializers alineados con el backend.",
    ),
    r"Grpc\.Core\.RpcException|Grpc\.Net\.Client\.Internal\.GrpcCall|StatusCode\.(Unavailable|DeadlineExceeded|Unauthenticated)": _(
        "channel = GrpcChannel.ForAddress(\"https://localhost:7\");  // mal puerto",
        "Health del servidor gRPC; credenciales y deadline en CallOptions",
        "Llamada gRPC falló (red, auth, deadline).",
        "SocketsHttpHandler, TLS y metadata de autorización.",
    ),
    r"Yarp\.ReverseProxy\.Forwarder\.|IForwarderErrorFeature|502 Bad Gateway.*YARP": _(
        "// cluster destination caído",
        "Health probe activo; HttpClient timeout razonable en cluster config",
        "YARP no pudo obtener respuesta válida del destino.",
        "Revisá ForwarderRequest y errores en IForwarderErrorFeature.",
    ),
    r"Microsoft\.AspNetCore\.RateLimiting\.|RateLimiterOptions|StatusCode:\s*429": _(
        "for (i...) client.GetAsync(\"/api\")  // supera ventana",
        "AddRateLimiter + PartitionByUser; cliente con backoff",
        "Rate limiting devolvió 429.",
        "Políticas por usuario/IP; Retry-After en respuesta.",
    ),
    r"Microsoft\.AspNetCore\.SignalR\.HubException|HubException|Cannot send message.*connection": _(
        "Clients.Group(\"x\").SendAsync(...)  // grupo vacío o hub mal tipado",
        "await Groups.AddToGroupAsync(Context.ConnectionId, \"x\");",
        "SignalR: conexión cerrada o error en método del Hub.",
        "Manejo de OnDisconnected; protocolo JSON vs MessagePack unificado.",
    ),
    r"Microsoft\.AspNetCore\.Components\.|JSException|RemoteRendererException|blazor": _(
        "@inject IJSRuntime JS\nawait JS.InvokeVoidAsync(\"noExiste\");",
        "Exportá función JS global o usa import dinámico coherente con Blazor",
        "Blazor: circuito roto o interop JS falló.",
        "DetailedErrors en desarrollo; no captures IJSObjectReference tras dispose.",
    ),
    r"Microsoft\.AspNetCore\.Mvc\.Razor\.|Razor\.RuntimeCompilation|ViewEngineResult": _(
        "return View(\"VistaInexistente\");",
        "Vista en Views/Controller/Action.cshtml con nombre correcto",
        "Vista Razor no encontrada o error de compilación .cshtml.",
        "AddRazorRuntimeCompilation en dev; _ViewImports y layout.",
    ),
    r"Microsoft\.AspNetCore\.Diagnostics\.DeveloperExceptionPage|DeveloperExceptionPageMiddleware": _(
        "// excepción no manejada en Development",
        "app.UseExceptionHandler(\"/error\") en Production",
        "Página de desarrollo mostró stack trace.",
        "En prod usá handler genérico y logs estructurados.",
    ),
    r"Microsoft\.AspNetCore\.Http\.HttpResults\.|IResult": _(
        "Results.File(stream, \"a.txt\")  // stream ya cerrado",
        "Abrir stream válido o Results.File(path)",
        "Minimal API IResult recibió argumentos inválidos.",
        "TypedResults y OpenAPI metadata para tipos de respuesta.",
    ),
    r"Microsoft\.Extensions\.Options\.OptionsValidationException|ValidateDataAnnotations|ValidateOnStart": _(
        "services.Configure<MyOpt>(o => o.Url = \"bad\");",
        "class MyOpt { [Required] public string Url { get; set; } }",
        "IOptions<T> falló validación al arranque.",
        "ValidateOnStart + IValidateOptions para mensajes claros.",
    ),
    r"System\.Net\.Http\.HttpRequestException|TaskCanceledException.*HttpClient": _(
        "client.GetAsync(\"http://host-inexistente\")",
        "IHttpClientFactory + DNS correcto; Polly para transitorios",
        "HttpClient: red, DNS o timeout.",
        "No instancies HttpClient por request; named clients y timeouts explícitos.",
    ),
    r"Microsoft\.Extensions\.Diagnostics\.HealthChecks\.|Health check.*with status Unhealthy": _(
        "AddCheck(\"db\", () => HealthCheckResult.Unhealthy());",
        "return Healthy si dependencia OK; Degraded si opcional falla",
        "Health check marcó Unhealthy (k8s puede reiniciar el pod).",
        "Separá readiness vs liveness; checks ligeros en hot path.",
    ),
    r"OpenIddict\.[A-Za-z_.]+Exception|OpenIddictCoreBuilder": _(
        "// cliente OAuth sin redirect_uri registrado",
        "OpenIddictApplicationManager.CreateAsync con redirect URIs",
        "OpenIddict rechazó token, cliente o scope.",
        "Logs de validación y permisos de endpoints de token.",
    ),
    r"Duende\.IdentityServer\.|IdentityServer4\.|invalid_scope|invalid_client": _(
        "client_id o secret incorrecto en token request",
        "Client config: AllowedGrantTypes, RedirectUris, Secrets",
        "STS Duende/IdentityServer rechazó la petición OAuth/OIDC.",
        "Revisá discovery document y parámetros del token endpoint.",
    ),
    r"Microsoft\.AspNetCore\.Identity\.|UserManager|SignInManager|IdentityError": _(
        "await userManager.CreateAsync(user, \"123\");  // password débil",
        "PasswordOptions alineadas con política de negocio",
        "Identity: creación de usuario o sign-in falló.",
        "IdentityResult.Errors en respuesta API; lockout y 2FA.",
    ),
    r"WebApplicationFactory|Microsoft\.AspNetCore\.Mvc\.Testing\.|TestServer": _(
        "new WebApplicationFactory<Program>().CreateClient();  // Program internal",
        "public partial class Program { }  // o InternalsVisibleTo",
        "Factory de integración no pudo crear el host o content root.",
        "ConfigureWebHost; sustituí DbContext por InMemory en tests.",
    ),
    r"Microsoft\.EntityFrameworkCore\.DbUpdateException.*inner|RetryLimitExceededException": _(
        "SaveChanges con ExecutionStrategy y transacción manual incompatible",
        "Usá la estrategia de ejecución envolviendo toda la transacción",
        "EF agotó reintentos ante error transitorio.",
        "InnerException SQL real; EnableRetryOnFailure con política adecuada.",
    ),
    r"Microsoft\.EntityFrameworkCore\.Infrastructure\.|RelationalEventId\.|SqliteException": _(
        "// SQLite database locked",
        "Connection string: Cache=Shared; Default Timeout=30",
        "Provider EF o SQLite reportó error de infraestructura.",
        "Migraciones aplicadas; WAL y timeouts para concurrencia.",
    ),
    r"MySqlConnector\.MySqlException|MySql\.Data\.MySqlClient\.MySqlException": _(
        "// error 1213 deadlock",
        "Reintento transitorio o orden consistente de locks",
        "MySQL devolvió error al ejecutar comando.",
        "SqlState / número de error MySQL en la excepción.",
    ),
    r"Microsoft\.Data\.Sqlite\.SqliteException": _(
        "File.OpenRead(\"locked.db\") mientras EF escribe",
        "Un writer o usar modo shared",
        "SQLite desde Microsoft.Data.Sqlite falló.",
        "BusyTimeout; no mezclar procesos sin shared cache.",
    ),
    r"Oracle\.ManagedDataAccess|OracleException": _(
        "// ORA-12154 TNS",
        "tnsnames.ora o Easy Connect con host/puerto correctos",
        "Oracle database rechazó la operación.",
        "Código ORA-xxxxx en mensaje y documentación Oracle.",
    ),
    r"MassTransit\.(RequestFaultException|RequestTimeoutException)|RabbitMQ\.Client\.Exceptions": _(
        "requestClient.GetResponse<Resp>(msg)  // consumidor lanzó",
        "Manejo de fault; timeout mayor o idempotencia en handler",
        "Bus de mensajes: fault, timeout o conexión AMQP.",
        "Logs de receive endpoint; dead-letter y reintentos.",
    ),
    r"Hangfire\.(Common|BackgroundJob|Server)\.|JobAbortedException|BackgroundJobClientException": _(
        "BackgroundJob.Enqueue(() => MetodoQueTira());",
        "Filtro de excepciones o fix del job; dashboard para ver fallos",
        "Hangfire no pudo encolar o el job falló repetidamente.",
        "Storage SQL/Redis; retries y servidor activo.",
    ),
    r"Quartz\.(JobExecutionException|SchedulerException)": _(
        "cron \"0 0 31 2 *\"  // fecha inválida",
        "Expresión cron válida o SimpleScheduleBuilder",
        "Quartz: job o scheduler en estado inválido.",
        "DisallowConcurrentExecution; misfire policy.",
    ),
    r"Serilog\.Core\.|SelfLog\.|LoggerConfiguration": _(
        "WriteTo.File(\"/root/logs/...\")  // sin permiso",
        "Ruta escribible o SelfLog para ver fallos del sink",
        "Serilog sink falló al emitir evento.",
        "SelfLog.Enable; validá permisos y formato de template.",
    ),
    r"OpenTelemetry\.|ActivitySource|MeterProvider": _(
        "AddOtlpExporter sin OTEL_EXPORTER_OTLP_ENDPOINT",
        "Variable de entorno o UseOtlpExporter con endpoint",
        "Exportador OTLP o provider OTEL mal configurado.",
        "Diagnostics en consola; sampling y recursos del servicio.",
    ),
    r"Humanizer\.|PluralizationService": _(
        "Pluralize(\"child\")  // cultura en-US",
        "Especificá cultura o cadena fija para UI crítica",
        "Humanizer: operación de texto/cultura inesperada.",
        "CurrentUICulture y pruebas con culturas objetivo.",
    ),
    r"MimeKit\.|MailKit\.(Net\.|Security\.)": _(
        "client.Connect(\"smtp\", 587, false)  // STARTTLS requerido",
        "SecureSocketOptions.StartTls cuando el servidor lo exige",
        "Cliente SMTP/IMAP falló (TLS, auth).",
        "Certificados y modos de socket seguros.",
    ),
    r"SixLabors\.ImageSharp\.|ImageProcessingException": _(
        "Image.Load(streamCorrupto)",
        "Validá magic bytes; límites MaxWidth/MaxHeight",
        "ImageSharp no pudo decodificar o límites excedidos.",
        "Identify antes de Decode; tamaño máximo por petición.",
    ),
    r"AWSSDK\.|Amazon\.(S3|DynamoDB|Runtime)\.": _(
        "AmazonS3Client sin credenciales en EC2",
        "IAM role en instancia o cadena de credenciales explícita",
        "AWS SDK devolvió error de servicio o throttling.",
        "AmazonServiceException.ErrorCode y reintentos adaptativos.",
    ),
    r"Azure\.(Core|Identity|Storage)\.|RequestFailedException": _(
        "new BlobClient(uriSinAuth)",
        "DefaultAzureCredential o connection string con permisos",
        "Azure SDK: 401/403 o recurso inexistente.",
        "Status, ErrorCode y cadena de identidad en la nube.",
    ),
    r"Stripe\.StripeException|Stripe\.Error": _(
        "PaymentMethod.Attach sin customer",
        "Flujo PaymentIntent + confirm según docs Stripe",
        "API de Stripe rechazó la operación.",
        "StripeError.Type/Code; webhooks con signing secret.",
    ),
    r"KubernetesClient\.|k8s\.(Autorest\.)?KubernetesException": _(
        "client.ListNamespacedPod(\"ns-inexistente\")",
        "Namespace existe; kubeconfig y contexto correctos",
        "API de Kubernetes rechazó la llamada.",
        "HTTP status en inner; RBAC del ServiceAccount.",
    ),
    r"Docker\.DotNet\.DockerApiException": _(
        "client.Containers.CreateContainerAsync(...)  // imagen no existe",
        "docker pull previo o tag correcto",
        "Docker daemon rechazó la operación.",
        "Mensaje de la API; versión de API del client vs daemon.",
    ),
    r"NSwag\.|NJsonSchema\.JsonSchemaException": _(
        "// tipo con ciclo infinito en OpenAPI",
        "[JsonIgnore] o SchemaProcessor para romper ciclo",
        "NSwag/NJsonSchema no pudo generar schema.",
        "Referencias y tipos primitivos explícitos en DTOs.",
    ),
    r"Swashbuckle\.AspNetCore\.SwaggerGen\.SwaggerGeneratorException": _(
        "dos DTO distintos con mismo nombre corto",
        "CustomSchemaIds(type => type.FullName)",
        "Swashbuckle no pudo generar documento único.",
        "ProducesResponseType y conflictos de OperationId.",
    ),
    r"Microsoft\.AspNetCore\.OpenApi\.|OpenApiOperationTransformer": _(
        "WithOpenApi en endpoint con tipo anónimo problemático",
        "DTO con nombre estable o transformer de schema",
        "OpenAPI integrado falló al transformar operación o schema.",
        "AddOpenApi documentación MS; transformers registrados.",
    ),
    r"ProblemDetails|IProblemDetailsService|ValidationProblemDetails": _(
        "return Results.BadRequest(\"texto plano\");",
        "return Results.ValidationProblem(errors);  // problem+json",
        "Cliente esperaba problem+json coherente con RFC 7807.",
        "AddProblemDetails; Title, Detail, Instance útiles.",
    ),
    r"Wolverine\.|JasperFx": _(
        "// handler lanza sin dead-letter configurado",
        "PersistMessageStore + política de reintentos",
        "Wolverine falló al manejar o enrutar mensaje.",
        "Documentación JasperFx: durabilidad y transport.",
    ),
    r"Rebus\.|Rebus\.Exceptions": _(
        "Configure.With(...) sin transport",
        "UseRabbitMq o SQL transport con connection string",
        "Rebus no pudo enviar/recibir del transport.",
        "Error queue y segunda cola para poison messages.",
    ),
}

__all__ = ["CAPSULES_CSHARP_HANDWRITTEN"]
