# Fichas --man adicionales para JavaScript/TS (prioridad alta): patrones en patterns/ no cubiertos en handwritten_extra.
# Claves = regex exactas de explain/patterns/js_ts.py, js_warnings.py, js_frameworks.py

from __future__ import annotations

from typing import Any


def _(
    mal: str,
    bien: str,
    que: str,
    regla: str,
) -> dict[str, Any]:
    return {
        "codigo_incorrecto": mal,
        "codigo_correcto": bien,
        "que_paso": que,
        "regla": regla,
    }


CAPSULES_JS_PRIORITY: dict[str, dict[str, Any]] = {
    r"TS2304:|Cannot find name": _(
        "console.log(foo);",
        "const foo = 1;  // o import { foo }",
        "El nombre no está declarado en este ámbito de tipos.",
        "`import`/`export`, `declare global`, o `@types/*` faltante.",
    ),
    r"TS2345:|Argument of type": _(
        "fn(123 as any);  // mal modelo",
        "fn(valorCorrecto);  // o genéricos explícitos",
        "El argumento no encaja con la firma esperada.",
        "`satisfies`, narrowing, o sobrecargas alineadas al tipo real.",
    ),
    r"TS18046:|is of type 'unknown'": _(
        "function f(x: unknown) { return x.foo; }",
        "if (typeof x === 'object' && x && 'foo' in x) ...",
        "Usás `unknown` sin acotar el tipo.",
        "`typeof`/`instanceof`, Zod/io-ts, o `as` con criterio.",
    ),
    r"TS7006:|implicitly has an 'any' type": _(
        "function f(x) { return x; }",
        "function f(x: string) { return x; }",
        "`noImplicitAny`: parámetro sin anotación.",
        "Tipá parámetros y retornos; inferencia desde default si aplica.",
    ),
    r"TS7053:|element implicitly has an 'any' type": _(
        "obj[key]  // key: string libre",
        "Record<string, T> o keyof typeof obj",
        "Indexación sin firma de índice en el tipo.",
        "`Record<K,V>`, `keyof`, o `as const` + `satisfies`.",
    ),
    r"TS2614:|Module .* has no exported member": _(
        "import { x } from './m';",
        "// m.ts: export { x } o export default",
        "Import nombrado que el módulo no exporta.",
        "Revisá `export` del módulo y default vs named.",
    ),
    r"TS1208:|compilable module": _(
        "// archivo sin import ni export",
        "export {};  // fuerza módulo",
        "El archivo se trata como script global, no como módulo.",
        "`export {}` o `import`/`export` top-level; `isolatedModules`.",
    ),
    r"TS1378:|Top-level await": _(
        "await fetch('/');",
        "// tsconfig: module esnext + target adecuado, o IIFE async",
        "El target/module no soporta top-level await.",
        "`module: esnext` o wrapper async.",
    ),
    r"TS2786:|JSX element implicitly has type 'any'": _(
        "// sin @types/react",
        "npm i -D @types/react @types/react-dom; jsx: react-jsx",
        "Falta configuración JSX o tipos de React.",
        "`jsx` en tsconfig y tipos instalados.",
    ),
    r"TS2305:|Module .* has no exported member": _(
        "import { missing } from 'pkg';",
        "Revisá exports del paquete y versión de @types",
        "El módulo no exporta ese nombre (similar a TS2614).",
        "Documentación del paquete y `exports` en package.json.",
    ),
    r"TS2769:|No overload matches this call": _(
        "fn(1, 'a', true);  // ninguna sobrecarga",
        "Ajustá argumentos o cast explícito documentado",
        "Ninguna sobrecarga encaja con los argumentos.",
        "Genéricos explícitos o firma correcta de la API.",
    ),
    r"TS2352:|Conversion of type .* may be a mistake": _(
        "x as VeryOther",
        "unknown como intermedio o corregí el modelo",
        "`as` entre tipos que no se solapan.",
        "Narrowing real o `unknown` intermedio.",
    ),
    r"TS2415:|Class .* incorrectly extends": _(
        "class A extends B {}  // props privadas incompatibles",
        "`implements` o alineá visibilidad con la base",
        "La clase base no es extensible de esa forma.",
        "`implements` vs `extends`; reglas de privados.",
    ),
    r"TS2515:|Non-abstract class .* does not implement": _(
        "class C implements I {}",
        "Implementá todos los miembros de I o abstract class",
        "Falta implementar miembro de interfaz.",
        "Completá la interfaz o marcá la clase abstracta.",
    ),
    r"TS2698:|Spread types may only be created from object types": _(
        "{ ...42 }",
        "{ ...obj }  // obj es objeto",
        "Spread sobre un valor que no es objeto.",
        "Asegurá objeto; no mezcles spread de array con objeto sin criterio.",
    ),
    r"TS2741:|Property .* is missing in type": _(
        "const o: { a: number } = {};",
        "const o = { a: 1 };",
        "Objeto literal no cumple el tipo (excess/missing checks).",
        "Todas las propiedades requeridas o `satisfies`.",
    ),
    r"TS2320:|Interface .* cannot simultaneously extend": _(
        "interface X extends A, B {}  // prop conflicto",
        "Renombrá o intersection type",
        "Dos bases declaran la misma propiedad con tipos distintos.",
        "Unificar nombres o usar tipos compuestos.",
    ),
    r"TypeError:.*is not iterable": _(
        "for (const x of maybeNull) {}",
        "for (const x of Array.from(maybeNull ?? [])) {}",
        "`for..of` sobre no-iterable.",
        "`Array.from`, `Symbol.iterator`, o comprobación previa.",
    ),
    r"SyntaxError: (Unexpected token|Invalid or unexpected token)": _(
        "const x = { a: 1, }",
        "JSON.parse('{')",
        "Parser JS falla (JSON inválido, JSX sin transpilar, etc.).",
        "JSON válido; transpile JSX/TS con la toolchain correcta.",
    ),
    r"ERR_REQUIRE_ESM|Must use import to load ES Module": _(
        "require('pkg-esm-only')",
        "import('pkg-esm-only')  // o type module",
        "`require()` sobre paquete solo ESM.",
        "Dynamic `import()` o proyecto ESM.",
    ),
    r"ERR_MODULE_NOT_FOUND": _(
        "import './file'  // falta .js en Node ESM",
        "import './file.js' con extensiones explícitas",
        "Resolución ESM fallida en Node.",
        "Extensiones en imports relativos; campo `exports`.",
    ),
    r"EADDRINUSE|address already in use": _(
        "server.listen(3000)  // ocupado",
        "Otro puerto o libera el proceso anterior",
        "Puerto ya en uso.",
        "`lsof -i :PORT` o variable de entorno para el puerto.",
    ),
    r"ENOTFOUND|getaddrinfo": _(
        "fetch('https://typo-host')",
        "Corregí hostname y DNS/red",
        "El nombre no resolvió.",
        "Conectividad, VPN, typo en URL.",
    ),
    r"ETIMEDOUT|timeout": _(
        "await fetch(url, { signal: AbortSignal.timeout(1) })",
        "Timeouts más altos o red estable",
        "Conexión o lectura expiró.",
        "Firewall, servidor lento, timeouts configurables.",
    ),
    r"Maximum call stack size exceeded": _(
        "function f() { f(); } f();",
        "Caso base o versión iterativa",
        "Recursión infinita o ciclo de llamadas.",
        "Límite de profundidad; refactor a iterativo.",
    ),
    r"Unexpected end of JSON input|JSON\.parse": _(
        "JSON.parse('')",
        "Validá que el string sea JSON completo",
        "Cadena truncada o vacía.",
        "Origen del payload y try/catch.",
    ),
    r"eslint|ESLint:": _(
        "// regla eslint -- error en CI",
        "eslint --fix o ajustá la regla con criterio",
        "Linter: estilo o calidad.",
        "Mensaje de la regla y configuración `.eslintrc`.",
    ),
    r"webpack|Module parse failed|Module not found: Error: Can't resolve": _(
        "// import de .svg sin loader",
        "Configurá loader/alias en webpack",
        "Webpack no pudo parsear o resolver el módulo.",
        "Loaders, alias, dependencia instalada.",
    ),
    # Clave de js_ts.py (distinta de la de js_frameworks con prefijo \\[vite\\]).
    r"vite.*Failed to resolve|Rollup.*could not resolve": _(
        "// log sin corchetes: vite Could not resolve …",
        "npm i paquete; alias y optimizeDeps en vite.config.ts",
        "Vite/Rollup no resolvió el import (mensaje sin el prefijo `[vite]`).",
        "`resolve.alias`, `optimizeDeps.include`, peers instalados.",
    ),
    r"Jest:|jest.*Cannot find module": _(
        "jest.mock('modulo') mal mapeado",
        "moduleNameMapper en jest.config",
        "Jest no resuelve módulo o mock.",
        "`jest.config`, `transformIgnorePatterns`.",
    ),
    r"pnpm ERR!|npm ERR!|yarn error": _(
        "npm install  # fallo de red o peer",
        "Revisá log completo, lockfile, versión de Node",
        "Gestor de paquetes falló en install o script.",
        "Cache, registry, `engines` en package.json.",
    ),
    r"ExperimentalWarning|DeprecationWarning": _(
        "node --experimental-...",
        "Migrá a API estable o fijá versión de Node",
        "Node avisa API experimental u obsoleta.",
        "Notas de versión y `NODE_OPTIONS` si aplica.",
    ),
    r"BigInt|Cannot mix BigInt and other types": _(
        "1n + 1",
        "1n + 1n  // o Number(1n) si cabe",
        "Mezcla BigInt con Number sin conversión.",
        "Mantener todo BigInt o convertir explícitamente.",
    ),
    r"RegExp.*out of range|Invalid regular expression": _(
        "/[/]/",
        "Escapá caracteres especiales en el patrón",
        "Regex mal formada o flag incompatible.",
        "Modo `u`/`v` y escapes correctos.",
    ),
    r"import assertions|Import attribute": _(
        'import data from "./x.json"',
        'import data from "./x.json" with { type: "json" }',
        "Módulos JSON/CSS requieren atributo de tipo en algunos entornos.",
        "Sintaxis `with { type: \"json\" }` según runtime.",
    ),
    r"DOMException|SecurityError|NotAllowedError": _(
        "navigator.clipboard.writeText('')  // sin gesto",
        "Tras click del usuario o HTTPS",
        "API web bloqueada (CORS, permisos, contexto inseguro).",
        "HTTPS, headers CORS, user gesture.",
    ),
    r"RangeError: Invalid array length": _(
        "new Array(2**32)",
        "Longitud dentro del rango permitido",
        "`length` ilegal para arrays.",
        "Valores dentro de límites de V8.",
    ),
    r"AssertionError|Assertion failed": _(
        "assert.equal(1, 2)",
        "Corregí expectativa o datos del test",
        "Assert de Node o test runner falló.",
        "Mensaje Expected vs Actual.",
    ),
    r"TS2564:|Property.*has no initializer": _(
        "class C { x: number; }",
        "class C { x: number = 0; }  // o en constructor",
        "`strictPropertyInitialization`: propiedad sin valor.",
        "Inicializá en ctor, `!`, o relajá opción en tsconfig.",
    ),
    r"TS2451:|Cannot redeclare block-scoped variable": _(
        "let a = 1; let a = 2;",
        "let a = 1; a = 2;",
        "Dos `let`/`const` con el mismo nombre en el mismo bloque.",
        "Renombrá o usá bloques `{}` distintos.",
    ),
    r"TS2588:|Cannot assign to.*because it is a constant": _(
        "const x = 1; x = 2;",
        "let x = 1; x = 2;",
        "Reasignación a `const`.",
        "Usá `let` si debe mutar el binding.",
    ),
    r"TS2322:.*undefined is not assignable": _(
        "let s: string = undefined;",
        "let s: string | undefined = undefined;",
        "`undefined` no entra en el tipo estricto.",
        "Unión con `undefined` o valor por defecto.",
    ),
    r"ERR_SOCKET_|ECONNRESET|EPIPE|ENOTCONN": _(
        "socket.write después de close del peer",
        "Manejo en .on('error') y reconexión",
        "Socket TCP cerrado o pipe roto.",
        "Estado de la conexión y reintentos.",
    ),
    r"ERR_INVALID_ARG_TYPE|ERR_INVALID_ARG_VALUE": _(
        "fs.readFile(123)",
        "Pasar tipos que documenta la API de Node",
        "Node rechazó tipo o valor de argumento.",
        "Documentación de la función y `typeof` en depuración.",
    ),
    r"SyntaxError: The requested module|does not provide an export named": _(
        "import { x } from './cjs.cjs'",
        "Alineá ESM vs CJS: default vs named exports",
        "Import nombrado no existe en el módulo (CJS vs ESM).",
        "`import x from` vs `import { x }`; `module.exports`.",
    ),
    r"ReferenceError: require is not defined": _(
        "require('fs')  // en ESM",
        "import fs from 'node:fs';  // o createRequire",
        "`require` no existe en módulos ESM.",
        "`import` o `createRequire(import.meta.url)`.",
    ),
    r"TS1005:|TS1003:|TS1127:": _(
        "const x = { a: 1  // falta }",
        "Balanceá `{}`, `;`, genéricos y JSX",
        "Token faltante o sobrante en TypeScript.",
        "Línea anterior al error; `<>` en TSX vs genéricos.",
    ),
    r"TS1128:|TS1109:|TS1068:": _(
        "export const x = 1\n}\n",
        "Llaves y export al inicio del módulo coherentes",
        "Parser esperaba declaración o fin de bloque.",
        "Llaves balanceadas; estructura del archivo.",
    ),
    r"TS2551:.*Did you mean": _(
        "obj.lenght",
        "obj.length  // typo sugerido por tsc",
        "Propiedad inexistente; tsc sugiere nombre parecido.",
        "Aceptá la sugerencia o revisá el tipo.",
    ),
    r"TS2349:|This expression is not callable": _(
        "const x: {} | (() => void) = ...; x();",
        "Narrowing: typeof x === 'function'",
        "Llamás `()` algo que no es función en todos los casos de unión.",
        "Type guard o firma unificada.",
    ),
    r"TS2538:.*cannot be used as an index type": _(
        "obj[key]  // key: object",
        "Record<string, T> o keyof",
        "Tipo de clave de índice inválido.",
        "`keyof typeof` o restricciones genéricas.",
    ),
    r"ERR_PNPM_|pnpm:.*ERR_|ERR_SOCKET_TIMEOUT|ECONNREFUSED": _(
        "pnpm install  # registry o proxy",
        ".npmrc proxy/registry; firewall",
        "pnpm o red no pudo conectar.",
        "Conectividad y configuración de registry.",
    ),
    r"OutOfMemoryError|JavaScript heap out of memory|FATAL ERROR: Reached heap limit": _(
        "node build.js  # proceso enorme",
        "NODE_OPTIONS=--max-old-space-size=8192  // y optimizá memoria",
        "Heap de V8 agotado.",
        "Fugas, datasets grandes, límite de heap.",
    ),
    r"Playwright|Error: browserType\.|Executable doesn't exist": _(
        "npx playwright test  // sin browsers",
        "npx playwright install",
        "Falta binario del navegador de Playwright.",
        "`playwright install` y variables de entorno de browsers.",
    ),
    # --- TypeScript extra (js_ts.py) ---
    r"TS18048:": _(
        "function f(x?: string) { return x.length; }",
        "return x?.length ?? 0;",
        "Con `strictNullChecks`, `x` puede ser `undefined` y se usa sin comprobar.",
        "`?.`, `??`, `if (x !== undefined)` o tipo más estrecho.",
    ),
    r"TS18047:": _(
        "function f(x: string | null) { return x.toUpperCase(); }",
        "if (x != null) return x.toUpperCase();",
        "El valor puede ser `null` y se accede sin narrow.",
        "`if (x != null)`, `?.`, o contrato sin null si hay garantía.",
    ),
    r"TS2353:|Object literal may only specify known properties": _(
        "const o: { a: number } = { a: 1, extra: 2 };",
        "const o = { a: 1 };  // o ampliá el tipo / index signature",
        "El literal tiene propiedades que el tipo destino no declara.",
        "Quitá claves sobrantes, extendé el tipo, o `satisfies` con criterio.",
    ),
    r"TS2344:|does not satisfy the constraint": _(
        "function id<T extends { id: string }>(x: T) { return x; }\nid({ n: 1 });",
        "Pasá un objeto que cumpla `{ id: string }` o relajá `extends`.",
        "El argumento de tipo no cumple la restricción del genérico.",
        "Alineá el tipo concreto con `extends` o ajustá la restricción.",
    ),
    r"TS2300:|Duplicate identifier": _(
        "const x = 1;\nconst x = 2;",
        "Renombrá o unificá en una sola declaración",
        "Dos declaraciones con el mismo nombre en el mismo ámbito.",
        "Imports duplicados, merge de ramas, o copy-paste.",
    ),
    r"TS2739:|Type .* is missing the following properties": _(
        "const u: User = { name: 'a' };  // falta email, etc.",
        "Completá todas las propiedades requeridas o usá `Partial<User>`",
        "El objeto no tiene todas las propiedades obligatorias del tipo.",
        "Literal completo, opcionales `?`, o tipo parcial si aplica.",
    ),
    r"TS2740:": _(
        "const cfg: Config = {};",
        "Inicializá cada clave requerida o usá un tipo más permisivo",
        "Asignás un objeto vacío o incompleto donde se esperan muchas keys.",
        "`Record`, defaults por sección, o constructor que llene el objeto.",
    ),
    r"TS7016:|Could not find a declaration file": _(
        "import x from 'paquete-sin-types';",
        "npm i -D @types/paquete o `declare module 'paquete-sin-types';`",
        "No hay `.d.ts` para el módulo (ni en el paquete ni en DefinitelyTyped).",
        "`@types/*`, `declare module`, o `skipLibCheck` como último recurso.",
    ),
    r"TS7030:|Not all code paths return a value": _(
        "function f(x: boolean): number { if (x) return 1; }",
        "Añadí `return` en el else o `throw new Error('unreachable')`",
        "Algún camino de la función no devuelve el tipo prometido.",
        "Cubrí todos los caminos o cambiá el tipo de retorno a `void`.",
    ),
    r"TS2448:": _(
        "console.log(x);\nconst x = 1;",
        "const x = 1;\nconsole.log(x);",
        "`let`/`const`/`class` no se alzan como `var`; TDZ hasta la línea de declaración.",
        "Declará antes de usar.",
    ),
    r"TS2454:": _(
        "let x: number;\nconsole.log(x);",
        "let x = 0;  // o asigná en todas las ramas antes de leer",
        "Leés una variable antes de que el compilador vea asignación segura.",
        "Inicializá al declarar o asigná en cada rama.",
    ),
    r"TS2571:|Object is of type 'unknown'": _(
        "function use(u: unknown) { return u.foo; }",
        "if (typeof u === 'object' && u && 'foo' in u) ...",
        "Operás sobre `unknown` sin acotar (mensaje distinto a TS18046 según contexto).",
        "Type guards, Zod, o `unknown` → tipo con verificación.",
    ),
    r"TS2326:|Types of property.*are incompatible": _(
        "const a: { x: string } = { x: '1' };\nconst b: { x: number } = a;",
        "Alineá tipos de cada propiedad o usá mapeo explícito",
        "Dos tipos con la misma forma pero una propiedad choca en el tipo.",
        "Unión, genérico, o conversión explícita donde sea seguro.",
    ),
    r"TS2367:|This comparison appears to be unintentional": _(
        "if (status === 'ok' && status === 'err') { }",
        "Condición lógica coherente con los tipos posibles",
        "La comparación nunca puede ser verdadera o es redundante según tipos.",
        "Revisá literales, unions y narrowing.",
    ),
    r"TS2686:|React refers to a UMD global": _(
        "// JSX sin import y jsx: react",
        "import React from 'react';  // o jsx: react-jsx",
        "TS espera `React` en scope con la config JSX antigua.",
        "`import React` o migrá a `jsx: react-jsx` / `react-jsxdev`.",
    ),
    r"TS6192:|All imports in import declaration are unused": _(
        "import { a, b } from './m';",
        "import { a } from './m';  // quitá b",
        "`noUnusedLocals`: todo el import está sin usar.",
        "Eliminá imports muertos.",
    ),
    r"TS6196:|declared but never used": _(
        "function helper() {}",
        "Usá helper, eliminálo, o prefijo `_helper` si la firma es obligatoria",
        "Símbolo declarado y nunca referenciado (tsconfig estricto).",
        "Limpieza o `_` en parámetros intencionalmente ignorados.",
    ),
    # --- js_warnings.py ---
    r"^\(node:\d+\) Warning:": _(
        "(node:1) Warning: ...",
        "Leé el texto; actualizá flags o API según versión de Node",
        "Node emitió advertencia en stderr.",
        "Documentación de la feature señalada.",
    ),
    r"ExperimentalWarning:": _(
        "ExperimentalWarning: ...",
        "Evitá en prod crítico o fijá versión de Node",
        "API experimental de Node.",
        "Notas de versión y alternativas estables.",
    ),
    r"\d+:\d+\s+warning\s+": _(
        "src/a.ts:1:1  warning  no-unused-vars",
        "Corregí o desactivá la regla con criterio",
        "ESLint en nivel warn.",
        "Regla y archivo indicados en el mensaje.",
    ),
    r"Warning: The 'NO_COLOR'": _(
        "NO_COLOR=1 mytool",
        "Informativo de la CLI sobre colores",
        "Aviso de entorno (NO_COLOR u otro).",
        "Ignorá o configurá según la herramienta.",
    ),
    r"npm WARN": _(
        "npm WARN deprecated ...",
        "Lee el WARN; audit o actualización de deps",
        "npm avisa de peers, deprecations, scripts.",
        "Mensaje concreto y package.json.",
    ),
    r"yarn warning": _(
        "warning ...",
        "Revisá yarn.lock y resoluciones",
        "Yarn avisa de versiones o config.",
        "Documentación del mensaje.",
    ),
    r"tsconfig.*extends.*not found": _(
        '"extends": "@foo/bar/tsconfig"',
        "Instalá el paquete o corregí la ruta del base",
        "El tsconfig base del `extends` no existe.",
        "Ruta relativa o dependencia dev correcta.",
    ),
    r"bun (warn|warning)|Bun\.v": _(
        "bun install  # warning",
        "Compará con node si el comportamiento difiere",
        "Bun: compatibilidad o resolución distinta.",
        "Mensaje completo de Bun.",
    ),
    r"deno (warn|WARNING)": _(
        "deno run --allow-net mod.ts",
        "Flags --allow-* e imports en deno.json",
        "Deno: permisos o deprecación.",
        "`deno.json` y permisos explícitos.",
    ),
    r"source map|Failed to parse source map": _(
        "// warning en build",
        "Generá .map en build o ignorá en prod",
        "No se pudo cargar/parsear source map.",
        "Configuración del bundler y archivos .map.",
    ),
    r"corepack (warn|WARNING)|Corepack is about to download": _(
        "corepack enable",
        "Fijá packageManager en package.json",
        "Corepack va a descargar yarn/pnpm.",
        "Versión explícita en package.json.",
    ),
    r"WARN.*\[turbo\]|turbo.*WARN": _(
        "turbo run build",
        "turbo.json y workspaces",
        "Turborepo avisa de caché o dependencias.",
        "Documentación del mensaje concreto.",
    ),
    # --- js_frameworks.py (complemento) ---
    r"Warning:.*validateDOMNesting|cannot appear as a child of": _(
        "<p><p>texto</p></p>",
        "<div><p>...</p></div>",
        "Jerarquía HTML inválida en React.",
        "Fragment o contenedor válido según spec HTML.",
    ),
    r"Minified React error #|react\.dev/errors": _(
        "Minified React error #418",
        "Reproducí en dev o buscá el número en react.dev/errors",
        "En producción el mensaje de React está acortado.",
        "Build de desarrollo para el mensaje completo.",
    ),
    r"createRoot\(\)|ReactDOM\.render is no longer supported": _(
        "ReactDOM.render(<App />, root);",
        "createRoot(root).render(<App />);",
        "React 18 reemplazó `render` por `createRoot`.",
        "Guía de migración oficial de React 18.",
    ),
    r"invariant failed|Invariant:|NEXT_NOT_FOUND|NEXT_REDIRECT": _(
        "notFound() en Server Component",
        "Rutas app/ vs pages/ y uso de redirect/notFound",
        "Next.js abortó el render con invariant o navegación especial.",
        "Docs de App Router y cuándo usar notFound/redirect.",
    ),
    r"\[Vue warn\]|Vue\.warn": _(
        "[Vue warn]: ...",
        "Mensaje completo; Vue 2 vs 3",
        "Vue runtime: API deprecada o prop faltante.",
        "eslint-plugin-vue y documentación de versión.",
    ),
    r"Unknown custom element|Failed to resolve component": _(
        "<MiTag /> sin registrar",
        "components: { MiTag } o auto-import",
        "Componente Vue no registrado o import olvidado.",
        "Registro global/local en SFC.",
    ),
    r"@prisma/client did not initialize|Prisma schema validation": _(
        "import { PrismaClient } from '@prisma/client'",
        "npx prisma generate && prisma validate",
        "Cliente Prisma sin generate o schema inválido.",
        "`DATABASE_URL`, `binaryTargets`, schema.",
    ),
    r"\[vite\].*Internal server error|Transform failed": _(
        "[vite] Internal server error",
        "Stack del plugin; tsconfig jsx",
        "Vite no transformó el archivo (TS/JSX/CSS).",
        "Extensión en import y plugins.",
    ),
    r"esbuild.*error|ERROR:.*esbuild": _(
        "ERROR: esbuild: ...",
        "Sintaxis del archivo señalado; external en config",
        "esbuild falló al transpilar o empaquetar.",
        "Mensaje de línea/columna de esbuild.",
    ),
    r"Module not found:.*Can't resolve 'react'|Can't resolve 'react-dom'": _(
        "Can't resolve 'react'",
        "npm ls react; una sola versión; resolutions",
        "react no está en node_modules o hay duplicados.",
        "`npm ls`, overrides en monorepo.",
    ),
}

__all__ = ["CAPSULES_JS_PRIORITY"]
